"""
Production Live Trading Engine — Event-Driven Version.

This refactored engine uses the QuantumTrade event bus (Redis Streams) for
all inter-component communication. It publishes and subscribes to events
instead of direct method calls.

Key changes (Phase 1):
- Engine publishes SignalEvents (generated by strategy)
- Engine subscribes to OrderEvents (from risk manager)
- Engine publishes TradeEvents (after broker fill)
- All communication via Redis Streams (durable, replayable)

Public API remains unchanged — existing code works without modification.
"""

from __future__ import annotations  # For postponed evaluation of type hints

import time
from datetime import datetime
from typing import TYPE_CHECKING, Dict, List, Optional

import pandas as pd

# Tracing imports
from tracing.context import get_trace_id
from monitoring.tracing import setup_tracing, get_tracer

from brokers import get_broker
from brokers.base import BrokerOrder, OrderSide, OrderType, BaseBroker
from strategy import get_strategy, BaseStrategy
from risk.risk_manager import RiskManager
from config.settings import settings
from notifications import NotificationManager
from scheduler import TradingScheduler
from scheduler.market_hours import MarketType
from database import get_db
from database.trade_repository import TradeRepository
from monitoring.structured_logging import get_logger

try:
    from monitoring.metrics import (
        TRADING_TICKS_TOTAL,
        SIGNALS_GENERATED_TOTAL,
        STRATEGY_CONFIDENCE,
        TRADING_TICK_DURATION_SECONDS,
        ACTIVE_POSITIONS_COUNT,
        PORTFOLIO_VALUE_USD,
        CASH_BALANCE_USD,
    )
    METRICS_AVAILABLE = True
except Exception:
    METRICS_AVAILABLE = False
    class _NoOpMetric:
        def labels(self, *args, **kwargs):
            return self
        def inc(self, *args, **kwargs):
            pass
        def set(self, *args, **kwargs):
            pass
        def observe(self, *args, **kwargs):
            pass
    TRADING_TICKS_TOTAL = SIGNALS_GENERATED_TOTAL = STRATEGY_CONFIDENCE = TRADING_TICK_DURATION_SECONDS = ACTIVE_POSITIONS_COUNT = PORTFOLIO_VALUE_USD = CASH_BALANCE_USD = _NoOpMetric()

# Lazy import for event system
if TYPE_CHECKING:
    from quantumtrade.events import MessageBus

logger = get_logger(__name__)


class LiveTradingEngine:
    """
    Production-grade live trading engine with event-driven architecture.

    Responsibilities:
      1. Connect to broker
      2. Fetch market data → publish MarketDataEvent
      3. Subscribe to SignalEvent (from strategy/risk)
      4. Subscribe to OrderEvent → execute → publish TradeEvent
      5. Manage portfolio & send notifications
    """

    def __init__(
        self,
        broker_name: str = "paper",
        strategy_name: str = "EMA Crossover",
        symbols: Optional[List[str]] = None,
        interval_seconds: int = 300,
        # Broker config
        api_key: str = "",
        api_secret: str = "",
        paper: bool = True,
        # Notification config
        telegram_token: str = "",
        telegram_chat_id: str = "",
        discord_webhook_url: str = "",
        email_smtp_host: str = "",
        email_user: str = "",
        email_password: str = "",
        email_to: str = "",
        # NEW: Event bus (optional, auto-detected if None)
        message_bus: Optional[MessageBus] = None,
    ):
        self.symbols = symbols or settings.SYMBOLS
        self.interval = interval_seconds
        self._trade_count = 0
        self._start_time: Optional[datetime] = None
        self._event_mode = False  # Will be set after bus init

        # ── Event bus ──────────────────────────────────────────────
        # Auto-detect event system if not explicitly provided
        if message_bus is not None:
            self.message_bus = message_bus
            self._event_mode = True
        else:
            try:
                from quantumtrade.events import get_message_bus
                self.message_bus = get_message_bus(settings.MESSAGE_BUS_URL)
                if not hasattr(self.message_bus, "start_consumer") or not callable(self.message_bus.start_consumer):
                    raise RuntimeError("MessageBus implementation incomplete")
                self._event_mode = True
                logger.info("Event-driven mode auto-enabled (Redis available)")
            except ImportError:
                logger.warning("Event system not installed — using legacy direct mode")
                self.message_bus = None
                self._event_mode = False
            except Exception as e:
                logger.warning(f"Event system initialization failed: {e}. Falling back to direct mode.")
                self.message_bus = None
                self._event_mode = False

        # ── Initialize components ─────────────────────────────────

        # 1. Broker
        self.broker: BaseBroker = get_broker(
            broker_name,  # positional argument 'name'
            api_key=api_key or settings.API_KEY or "",
            api_secret=api_secret or settings.API_SECRET or "",
            paper=paper,
            initial_capital=settings.INITIAL_CAPITAL,
        )

        # 2. Strategy
        self.strategy: BaseStrategy = get_strategy(strategy_name)

        # 3. Risk Manager
        self.risk_manager = RiskManager(
            max_position_pct=settings.MAX_POSITION_SIZE_PCT,
            stop_loss_pct=settings.STOP_LOSS_PCT,
            max_daily_loss_pct=settings.MAX_DAILY_LOSS_PCT,
        )

        # 4. Notifications
        self.notifier = NotificationManager(
            telegram_token=telegram_token,
            telegram_chat_id=telegram_chat_id,
            discord_webhook_url=discord_webhook_url,
            email_smtp_host=email_smtp_host,
            email_user=email_user,
            email_password=email_password,
            email_to=email_to,
        )

        # 5. Scheduler
        market_type = MarketType.CRYPTO if "binance" in broker_name.lower() else MarketType.STOCKS
        self.scheduler = TradingScheduler(
            interval_seconds=interval_seconds,
            market_type=market_type,
            respect_market_hours=(market_type == MarketType.STOCKS),
        )

        # 6. Database
        self.db = get_db()
        self.trade_repo = TradeRepository(self.db)

        # ── Event subscriptions ──────────────────────────────────
        if self.message_bus:
            # Subscribe to order events (from risk/direct)
            self.message_bus.subscribe(
                "events:orders",
                self._handle_order_event
            )
            logger.info("Subscribed to order events on events:orders")

        logger.info(
            f"⚡ LiveTradingEngine initialized\n"
            f"   Broker: {broker_name} ({'PAPER' if paper else 'LIVE'})\n"
            f"   Strategy: {strategy_name}\n"
            f"   Symbols: {self.symbols}\n"
            f"   Notifications: {self.notifier.channel_count} channels\n"
            f"   Mode: {'Event-Driven' if self.message_bus else 'Legacy Direct'}"
        )

    # ── Lifecycle ─────────────────────────────────────────────────

    def start(self) -> None:
        """Connect to broker and start the trading loop."""
        self._start_time = datetime.now()

        # Connect broker
        if not self.broker.connect():
            logger.error("Failed to connect broker. Aborting.")
            self.notifier.send("🚨 Broker connection FAILED. Engine not started.", level="error")
            return

        # Log account info
        account = self.broker.get_account()
        startup_msg = (
            f"🚀 **QuantumTrade Engine Started**\n"
            f"💰 Capital: ${account.cash:,.2f}\n"
            f"📊 Equity: ${account.equity:,.2f}\n"
            f"🎯 Strategy: {self.strategy.name}\n"
            f"📈 Symbols: {', '.join(self.symbols)}"
        )
        logger.info(startup_msg)
        self.notifier.send(startup_msg, level="info")

        # Start message bus consumer (event-driven mode)
        if self.message_bus:
            logger.info("Starting event bus consumer...")
            self.message_bus.start_consumer(
                streams=["events:orders"],
                group=f"group:trading_engine:{self.broker.__class__.__name__}",
            )

        # Register tick callback (still uses scheduler)
        self.scheduler.on_tick(self._trading_tick)
        self.scheduler.on_market_open(self._on_market_open)
        self.scheduler.on_market_close(self._on_market_close)
        self.scheduler.on_error(lambda error: self.notifier.send(
            f"🚨 Engine error: {error}", level="error"
        ))

        # Start the scheduler (blocks until stop)
        try:
            self.scheduler.start()
        except KeyboardInterrupt:
            self.stop()

    def stop(self) -> None:
        """Gracefully stop the engine."""
        self.scheduler.stop()
        if self.message_bus:
            self.message_bus.stop_consumer()
        self.broker.disconnect()

        runtime = (datetime.now() - self._start_time).total_seconds() / 60 if self._start_time else 0
        stop_msg = (
            f"🛑 **Engine Stopped**\n"
            f"⏱️ Runtime: {runtime:.1f} minutes\n"
            f"📊 Trades executed: {self._trade_count}"
        )
        logger.info(stop_msg)
        self.notifier.send(stop_msg, level="info")

    # ── Trading Tick ─────────────────────────────────────────────────

    def _trading_tick(self) -> None:
        """Called by scheduler on every tick. Processes all symbols."""
        # Create tracer for this method
        tracer = get_tracer(__name__)
        with tracer.start_as_current_span("trading_tick", symbols_processed=len(self.symbols)):
            logger.info(f"🔔 Trading tick: processing {len(self.symbols)} symbols")
            tick_start = time.perf_counter()

            for symbol in self.symbols:
                try:
                    self._process_symbol(symbol)
                except Exception as e:
                    logger.error(f"Error processing {symbol}: {e}")
                    self.notifier.send(f"🚨 Error processing {symbol}: {e}", level="error")

            # Update portfolio metrics after processing all symbols
            self.update_portfolio_metrics()

            tick_duration = time.perf_counter() - tick_start
            logger.debug(f"Tick completed in {tick_duration:.2f}s")

    # ── Core Trading Logic ────────────────────────────────────────

    def _process_symbol(self, symbol: str) -> None:
        """Process a single symbol — fetch data, signal, trade."""
        start_time = time.perf_counter() if METRICS_AVAILABLE else None

        try:
            # 1. Fetch data
            data = self._fetch_data(symbol)
            if data is None or len(data) < self.strategy.get_required_periods():
                logger.warning(f"Insufficient data for {symbol}")
                if METRICS_AVAILABLE:
                    TRADING_TICKS_TOTAL.labels(symbol=symbol, outcome="skipped").inc()
                return

            # 2. Calculate indicators
            data = self.strategy.calculate_indicators(data)

            # 3. Generate signal
            signal = self.strategy.generate_signal(data, len(data) - 1)

            # Record signal metric
            if METRICS_AVAILABLE and hasattr(signal, 'signal_type'):
                SIGNALS_GENERATED_TOTAL.labels(
                    strategy=self.strategy.name,
                    signal_type=signal.signal_type
                ).inc()

                # Record confidence if available
                if hasattr(signal, 'confidence'):
                    STRATEGY_CONFIDENCE.labels(strategy=self.strategy.name).set(signal.confidence)

            if signal.is_hold():
                if METRICS_AVAILABLE:
                    TRADING_TICKS_TOTAL.labels(symbol=symbol, outcome="hold").inc()
                return

            # ── EVENT-DRIVEN PATH ───────────────────────────────────
            if self.message_bus:
                # Lazy import to avoid hard dependency when Redis not configured
                from quantumtrade.events import SignalEvent

                # Publish SignalEvent → consumed by SignalHandler → OrderHandler
                signal_event = SignalEvent(
                    source="trading_engine",
                    symbol=symbol,
                    strategy=self.strategy.name,
                    signal_type=signal.signal_type,
                    confidence=signal.confidence,
                    price=signal.price,
                    metadata={
                        "timestamp": signal.timestamp.isoformat() if hasattr(signal, 'timestamp') else datetime.now().isoformat(),
                        "interval": self.interval,
                    },
                )
                self.message_bus.publish(signal_event)
                logger.info(f"Published SignalEvent: {signal_event.signal_type} {symbol} @ ${signal.price:.2f}")

            # ── LEGACY DIRECT PATH (fallback) ────────────────────────
            else:
                # Direct mode: execute inline (existing logic)
                self._execute_signal_direct(symbol, signal)

            # Record successful tick
            if METRICS_AVAILABLE:
                TRADING_TICKS_TOTAL.labels(symbol=symbol, outcome="success").inc()

        except Exception as e:
            logger.exception(f"Error processing {symbol}: {e}")
            if METRICS_AVAILABLE:
                TRADING_TICKS_TOTAL.labels(symbol=symbol, outcome="error").inc()
            raise
        finally:
            # Record tick duration
            if METRICS_AVAILABLE and start_time is not None:
                duration = time.perf_counter() - start_time
                TRADING_TICK_DURATION_SECONDS.observe(duration)

    def _execute_signal_direct(self, symbol: str, signal) -> None:
        """Legacy direct execution path (unchanged logic)."""
        # 4. Get current position
        position = self.broker.get_position(symbol)
        account = self.broker.get_account()

        # 5. Decision logic (direct broker calls)
        if signal.is_buy() and not position:
            qty = self._calculate_position_size(
                symbol, signal.price, account.cash
            )
            if qty <= 0:
                return

            # Risk check
            if not self.risk_manager.check_trade(
                symbol=symbol,
                quantity=qty,
                price=signal.price,
                portfolio_value=account.portfolio_value,
            ):
                logger.info(f"⛔ Risk manager blocked BUY for {symbol}")
                return

            # Execute BUY
            order = BrokerOrder(
                symbol=symbol,
                side=OrderSide.BUY,
                quantity=qty,
                order_type=OrderType.MARKET,
                limit_price=signal.price,
            )
            result = self.broker.place_order(order)

            if result.is_filled:
                self._trade_count += 1
                fill_price = result.filled_price or signal.price

                # Log to database
                self.trade_repo.record_buy(
                    symbol=symbol,
                    quantity=qty,
                    price=fill_price,
                    strategy=self.strategy.name,
                    confidence=signal.confidence,
                    broker=self.broker.__class__.__name__,
                    order_id=result.order_id,
                )

                self.notifier.send_trade_alert(
                    symbol=symbol,
                    side="BUY",
                    quantity=qty,
                    price=fill_price,
                    strategy=self.strategy.name,
                )

        elif signal.is_sell() and position:
            order = BrokerOrder(
                symbol=symbol,
                side=OrderSide.SELL,
                quantity=position.quantity,
                order_type=OrderType.MARKET,
                limit_price=signal.price,
            )
            result = self.broker.place_order(order)

            if result.is_filled:
                self._trade_count += 1
                fill_price = result.filled_price or signal.price
                pnl = (fill_price - position.avg_entry_price) * position.quantity

                self.trade_repo.record_sell(
                    symbol=symbol,
                    quantity=position.quantity,
                    price=fill_price,
                    pnl=pnl,
                    strategy=self.strategy.name,
                    confidence=signal.confidence,
                    broker=self.broker.__class__.__name__,
                    order_id=result.order_id,
                )

                self.risk_manager.record_pnl(pnl)

                self.notifier.send_trade_alert(
                    symbol=symbol,
                    side="SELL",
                    quantity=position.quantity,
                    price=fill_price,
                    strategy=self.strategy.name,
                    pnl=pnl,
                )

    # ── Event Handlers (subscribe to events) ────────────────────

    def _handle_order_event(self, event: OrderEvent) -> None:
        """Handle incoming order event (from SignalHandler/Risk).

        In event-driven mode, receives OrderEvents and executes with broker.
        """
        try:
            logger.info(
                f"Received OrderEvent: {event.side} {event.quantity} {event.symbol} "
                f"id={event.order_id}"
            )

            # Convert to broker order
            broker_order = BrokerOrder(
                symbol=event.symbol,
                side=OrderSide.BUY if event.side == "BUY" else OrderSide.SELL,
                quantity=int(event.quantity),
                order_type=OrderType.MARKET if event.order_type == "MARKET" else OrderType.LIMIT,
                limit_price=event.limit_price,
            )

            # Execute with broker
            result = self.broker.place_order(broker_order)

            if result.is_filled:
                self._trade_count += 1
                fill_price = result.filled_price or broker_order.limit_price or 0

                # Log trade to DB
                self.trade_repo.record_buy(
                    symbol=event.symbol,
                    quantity=result.filled_quantity or event.quantity,
                    price=fill_price,
                    strategy=event.source,
                    confidence=1.0,
                    broker=event.broker,
                    order_id=result.order_id,
                )

                # Publish TradeEvent
                if self.message_bus:
                    from quantumtrade.events import TradeEvent

                    trade_event = TradeEvent(
                        source="trading_engine",
                        trade_id=result.order_id,
                        symbol=event.symbol,
                        side=event.side,
                        quantity=result.filled_quantity or event.quantity,
                        price=fill_price,
                        pnl=0.0,  # Calculated later by portfolio manager
                        strategy=event.source,
                        broker=event.broker,
                        order_id=event.order_id,
                    )
                    self.message_bus.publish(trade_event)

                # Notify
                self.notifier.send_trade_alert(
                    symbol=event.symbol,
                    side=event.side,
                    quantity=result.filled_quantity or event.quantity,
                    price=fill_price,
                    strategy=event.source,
                )

            else:
                logger.warning(f"Order not filled: {result.error}")

        except Exception as e:
            logger.exception(f"Error executing order event: {e}")
            self.notifier.send(f"🚨 Order execution error: {e}", level="error")

    # ── Helpers ────────────────────────────────────────────────────

    def _fetch_data(self, symbol: str, period: str = "60d") -> Optional[pd.DataFrame]:
        """Fetch historical data for a symbol using yfinance."""
        try:
            import yfinance as yf

            ticker = yf.Ticker(symbol)
            data = ticker.history(period=period, interval=settings.TIMEFRAME)

            if data is None or data.empty:
                return None

            # Standardise column names
            data.columns = [c.capitalize() for c in data.columns]
            return data

        except Exception as e:
            logger.error(f"Data fetch failed for {symbol}: {e}")
            return None

    def _calculate_position_size(
        self, symbol: str, price: float, cash: float
    ) -> float:
        """Calculate position size based on risk parameters."""
        max_allocation = cash * settings.MAX_POSITION_SIZE_PCT
        qty = max_allocation // price  # Whole shares for stocks

        if qty <= 0:
            logger.info(f"Position size 0 for {symbol} at ${price}")
            return 0

        return float(qty)

    def _on_market_open(self) -> None:
        """Called when market opens."""
        account = self.broker.get_account()
        self.notifier.send(
            f"🔔 **Market Open**\n"
            f"💰 Cash: ${account.cash:,.2f}\n"
            f"📊 Equity: ${account.equity:,.2f}\n"
            f"📈 Positions: {len(account.positions)}",
            level="info",
        )

    def _on_market_close(self) -> None:
        """Called when market closes."""
        account = self.broker.get_account()
        self.notifier.send(
            f"🔕 **Market Closed**\n"
            f"📊 Equity: ${account.equity:,.2f}\n"
            f"📈 Trades today: {self._trade_count}",
            level="info",
        )

    # ── Status ────────────────────────────────────────────────────

    def status(self) -> dict:
        """Get current engine status."""
        account = self.broker.get_account()
        status_dict = {
            "running": self.scheduler._running,
            "broker_connected": self.broker.is_connected,
            "strategy": self.strategy.name,
            "symbols": self.symbols,
            "trade_count": self._trade_count,
            "cash": account.cash,
            "equity": account.equity,
            "positions": len(account.positions),
            "uptime_minutes": (
                (datetime.now() - self._start_time).total_seconds() / 60
                if self._start_time else 0
            ),
            "mode": "event_driven" if self._event_mode else "direct",
        }

        # Update metrics if available
        if METRICS_AVAILABLE:
            try:
                ACTIVE_POSITIONS_COUNT.set(len(account.positions))
                PORTFOLIO_VALUE_USD.set(account.portfolio_value)
                CASH_BALANCE_USD.set(account.cash)
            except Exception as e:
                logger.debug(f"Failed to update portfolio metrics: {e}")

        return status_dict

    def update_portfolio_metrics(self) -> None:
        """Explicitly update portfolio-related metrics. Call on tick or on demand."""
        if not METRICS_AVAILABLE:
            return

        try:
            account = self.broker.get_account()
            ACTIVE_POSITIONS_COUNT.set(len(account.positions))
            PORTFOLIO_VALUE_USD.set(account.portfolio_value)
            CASH_BALANCE_USD.set(account.cash)
        except Exception as e:
            logger.debug(f"Failed to update portfolio metrics: {e}")
