{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantumtrade.fullname" . }}-grafana
  labels:
    {{- include "quantumtrade.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.monitoring.grafana.port }}
      targetPort: {{ .Values.monitoring.grafana.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "quantumtrade.name" . }}-grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quantumtrade.fullname" . }}-grafana
  labels:
    {{- include "quantumtrade.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quantumtrade.name" . }}-grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "quantumtrade.name" . }}-grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-enterprise:10.1.0
          ports:
            - containerPort: {{ .Values.monitoring.grafana.port }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.monitoring.grafana.adminPassword | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}