{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "quantumtrade.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}