apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantumtrade.fullname" . }}-tradingbot
  labels:
    {{- include "quantumtrade.labels" . | nindent 4 }}
    app.kubernetes.io/component: tradingbot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "quantumtrade.name" . }}-tradingbot
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantumtrade.fullname" . }}-model-serving
  labels:
    {{- include "quantumtrade.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-serving
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "quantumtrade.name" . }}-model-serving
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{ if .Values.mlflow.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quantumtrade.fullname" . }}-mlflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}